package template

// TwirpTemplates contains the methods used for building
// an app that uses [github.com/twitchtv/twirp]
type TwirpTemplates struct{}

func (t TwirpTemplates) Main() []byte {
	return MakeTwirpMain()
}
func (t TwirpTemplates) Server() []byte {
	return MakeTwirpServer()
}

func (t TwirpTemplates) Routes() []byte {
	return MakeHTTPRoutes()
}

func (t TwirpTemplates) ProtoFile() []byte {
	return MakeProtoFile()
}

// MakeTwirpServiceDefinition returns a byte slice that represents
// the internal/server/
func MakeProtoFile() []byte {
	return []byte(`syntax = "proto3"

    go_package = "twirp/hello_world"

    // HelloWorld service sends a personalized "hello world" message to clients
    service HelloWorld {
    rpc SayHelloTo(ClientName) returns (PersonalizedHelloWorld);
    }

    // The name of the client receiving the message
    message ClientName {
    string name = 1;
    }

    // The message returned to the clinent
    message PersonalizedHelloWorld {
    string msg = 1;
    }

    `)
}

// MakeTwirpMain returns a byte slice that represents
// the main.go file for Twirp implementation.
func MakeTwirpMain() []byte {
	return []byte(`
    package main

    import (
        "net/http"
        "github.com/twitchtv/twirp"
        "your/generated/protobuf"
        "your/twirp/handlers" // Handlers generated by Twirp
    )

    func main() {
        twirpHandler := your_twirp.NewYourServiceServer(&handlers.YourService{})
        mux := http.NewServeMux()
        mux.Handle(protobuf.YourServicePathPrefix, twirpHandler)

        // Start the server
        http.ListenAndServe(":8080", mux)
    }
    `)
}

// MakeTwirpServiceDefinition returns a byte slice that represents
// the internal/server/
func MakeTwirpServer() []byte {
	return []byte(`
    package your_twirp

    import (
        "context"
        "github.com/twitchtv/twirp"
        "your/generated/protobuf"
    )

    // YourService implements the generated protobuf YourService interface
    type YourService struct{}

    func (s *YourService) HelloWorld(ctx context.Context, req *protobuf.HelloRequest) (*protobuf.HelloResponse, error) {
        return &protobuf.HelloResponse{Message: "Hello, Twirp!"}, nil
    }
    `)
}
